name: Publish package

on:
    workflow_dispatch:
        inputs:
            publish_to_npm:
                description: "Publish package to NPM"
                required: false
                type: boolean
                default: true

permissions:
    contents: write
    id-token: write

jobs:
    publish_package:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Bun
              uses: oven-sh/setup-bun@v1

            - id: version
              name: Read package version
              run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

            - name: Install modules
              run: bun install

            - name: Type-check
              run: bun run typecheck

            - name: Build package
              run: bun run build

            - name: Publish package to NPM
              if: ${{ github.event.inputs.publish_to_npm }}
              run: bun publish --access public
              env:
                  NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: GitHub Release
              uses: ncipollo/release-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: v${{ steps.version.outputs.version }}
                  name: v${{ steps.version.outputs.version }}
                  draft: false
                  prerelease: false
                  generateReleaseNotes: true
